set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets m_3014_PCLK_IBUF]

#### CLOCK ####
##-- input --##
set_property PACKAGE_PIN N21		[get_ports m_sys_clk_160M_p]
set_property IOSTANDARD LVDS_25		[get_ports m_sys_clk_160M_p]
set_property DIFF_TERM false 		[get_ports m_sys_clk_160M_p]
set_property PACKAGE_PIN N22		[get_ports m_sys_clk_160M_n]
set_property IOSTANDARD LVDS_25		[get_ports m_sys_clk_160M_n]
set_property DIFF_TERM false 		[get_ports m_sys_clk_160M_n]

#### POWER ####
set_property PACKAGE_PIN H3			[get_ports m_power_OFF]
set_property IOSTANDARD LVCMOS33 	[get_ports {m_power_OFF}]

#### CYUSB CONTROL ####
##-- USB DATA --##
set_property PACKAGE_PIN H2			[get_ports m_3014_DQ[0 ]]
set_property PACKAGE_PIN K2			[get_ports m_3014_DQ[1 ]]
set_property PACKAGE_PIN M2			[get_ports m_3014_DQ[2 ]]
set_property PACKAGE_PIN J3			[get_ports m_3014_DQ[3 ]]
set_property PACKAGE_PIN K3			[get_ports m_3014_DQ[4 ]]
set_property PACKAGE_PIN L3			[get_ports m_3014_DQ[5 ]]
set_property PACKAGE_PIN K5			[get_ports m_3014_DQ[6 ]]
set_property PACKAGE_PIN L5			[get_ports m_3014_DQ[7 ]]
set_property PACKAGE_PIN M6			[get_ports m_3014_DQ[8 ]]
set_property PACKAGE_PIN N6			[get_ports m_3014_DQ[9 ]]
set_property PACKAGE_PIN L7			[get_ports m_3014_DQ[10]]
set_property PACKAGE_PIN M7			[get_ports m_3014_DQ[11]]
set_property PACKAGE_PIN N7			[get_ports m_3014_DQ[12]]
set_property PACKAGE_PIN N8			[get_ports m_3014_DQ[13]]
set_property PACKAGE_PIN R6			[get_ports m_3014_DQ[14]]
set_property PACKAGE_PIN L2			[get_ports m_3014_DQ[15]]
set_property PACKAGE_PIN T7			[get_ports m_3014_DQ[16]]
set_property PACKAGE_PIN P5			[get_ports m_3014_DQ[17]]
set_property PACKAGE_PIN U6			[get_ports m_3014_DQ[18]]
set_property PACKAGE_PIN T5			[get_ports m_3014_DQ[19]]
set_property PACKAGE_PIN R5			[get_ports m_3014_DQ[20]]
set_property PACKAGE_PIN U5			[get_ports m_3014_DQ[21]]
set_property PACKAGE_PIN U4			[get_ports m_3014_DQ[22]]
set_property PACKAGE_PIN T4			[get_ports m_3014_DQ[23]]
set_property PACKAGE_PIN R7			[get_ports m_3014_DQ[24]]
set_property PACKAGE_PIN M5			[get_ports m_3014_DQ[25]]
set_property PACKAGE_PIN T3			[get_ports m_3014_DQ[26]]
set_property PACKAGE_PIN U2			[get_ports m_3014_DQ[27]]
set_property PACKAGE_PIN N2			[get_ports m_3014_DQ[28]]
set_property PACKAGE_PIN K1			[get_ports m_3014_DQ[29]]
set_property PACKAGE_PIN H1			[get_ports m_3014_DQ[30]]
set_property PACKAGE_PIN J1			[get_ports m_3014_DQ[31]]

set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[0 ]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[1 ]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[2 ]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[3 ]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[4 ]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[5 ]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[6 ]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[7 ]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[8 ]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[9 ]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[10]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[11]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[12]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[13]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[14]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[15]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[16]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[17]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[18]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[19]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[20]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[21]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[22]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[23]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[24]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[25]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[26]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[27]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[28]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[29]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[30]]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_DQ[31]]

##-- USB Control --##
set_property PACKAGE_PIN R1			[get_ports m_3014_PCLK]
set_property PACKAGE_PIN P1			[get_ports m_3014_RAM_REN]
set_property PACKAGE_PIN R8			[get_ports m_3014_REN]
set_property PACKAGE_PIN P8			[get_ports m_3014_WEN]
set_property PACKAGE_PIN P6			[get_ports m_3014_POLLING_FLAG]
##set_property PACKAGE_PIN P3			[get_ports m_3014_CONFIG_COMPLETE]
##set_property PACKAGE_PIN U1			[get_ports m_3014_INT_L]
##set_property PACKAGE_PIN T8			[get_ports m_3014_GPIO23]

set_property IOSTANDARD LVCMOS33    [get_ports m_3014_PCLK]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_RAM_REN]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_REN]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_WEN]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_POLLING_FLAG]
##set_property IOSTANDARD LVCMOS33    [get_ports m_3014_CONFIG_COMPLETE]
##set_property IOSTANDARD LVCMOS33    [get_ports m_3014_INT_L]
##set_property IOSTANDARD LVCMOS33    [get_ports m_3014_GPIO23]

#### AFE ####
##-- AFE CLOCK --##
set_property PACKAGE_PIN AA20 		[get_ports m_AFE_FCLKP[0]]
set_property PACKAGE_PIN AB20 		[get_ports m_AFE_FCLKM[0]]
set_property PACKAGE_PIN AA19 		[get_ports m_AFE_DCLKP[0]]
set_property PACKAGE_PIN AB19 		[get_ports m_AFE_DCLKM[0]]
set_property PACKAGE_PIN U22 		[get_ports m_AFE_FCLKP[1]]
set_property PACKAGE_PIN V22 		[get_ports m_AFE_FCLKM[1]]
set_property PACKAGE_PIN U21 		[get_ports m_AFE_DCLKP[1]]
set_property PACKAGE_PIN V21 		[get_ports m_AFE_DCLKM[1]]
set_property PACKAGE_PIN K21		[get_ports m_AFE_FCLKP[2]]
set_property PACKAGE_PIN J21		[get_ports m_AFE_FCLKM[2]]
set_property PACKAGE_PIN H21		[get_ports m_AFE_DCLKP[2]]
set_property PACKAGE_PIN H22		[get_ports m_AFE_DCLKM[2]]
set_property PACKAGE_PIN D18		[get_ports m_AFE_FCLKP[3]]
set_property PACKAGE_PIN C18		[get_ports m_AFE_FCLKM[3]]
set_property PACKAGE_PIN D19		[get_ports m_AFE_DCLKP[3]]
set_property PACKAGE_PIN C19		[get_ports m_AFE_DCLKM[3]]
set_property IOSTANDARD LVDS_25		[get_ports m_AFE_FCLKP[0]]
set_property IOSTANDARD LVDS_25		[get_ports m_AFE_FCLKM[0]]
set_property IOSTANDARD LVDS_25		[get_ports m_AFE_DCLKP[0]]
set_property IOSTANDARD LVDS_25		[get_ports m_AFE_DCLKM[0]]
set_property IOSTANDARD LVDS_25		[get_ports m_AFE_FCLKP[1]]
set_property IOSTANDARD LVDS_25		[get_ports m_AFE_FCLKM[1]]
set_property IOSTANDARD LVDS_25		[get_ports m_AFE_DCLKP[1]]
set_property IOSTANDARD LVDS_25		[get_ports m_AFE_DCLKM[1]]
set_property IOSTANDARD LVDS_25		[get_ports m_AFE_FCLKP[2]]
set_property IOSTANDARD LVDS_25		[get_ports m_AFE_FCLKM[2]]
set_property IOSTANDARD LVDS_25		[get_ports m_AFE_DCLKP[2]]
set_property IOSTANDARD LVDS_25		[get_ports m_AFE_DCLKM[2]]
set_property IOSTANDARD LVDS_25		[get_ports m_AFE_FCLKP[3]]
set_property IOSTANDARD LVDS_25		[get_ports m_AFE_FCLKM[3]]
set_property IOSTANDARD LVDS_25		[get_ports m_AFE_DCLKP[3]]
set_property IOSTANDARD LVDS_25		[get_ports m_AFE_DCLKM[3]]
set_property DIFF_TERM false 		[get_ports m_AFE_FCLKP[0]]
set_property DIFF_TERM false 		[get_ports m_AFE_FCLKM[0]]
set_property DIFF_TERM false 		[get_ports m_AFE_DCLKP[0]]
set_property DIFF_TERM false 		[get_ports m_AFE_DCLKM[0]]
set_property DIFF_TERM false 		[get_ports m_AFE_FCLKP[1]]
set_property DIFF_TERM false 		[get_ports m_AFE_FCLKM[1]]
set_property DIFF_TERM false 		[get_ports m_AFE_DCLKP[1]]
set_property DIFF_TERM false 		[get_ports m_AFE_DCLKM[1]]
set_property DIFF_TERM false 		[get_ports m_AFE_FCLKP[2]]
set_property DIFF_TERM false 		[get_ports m_AFE_FCLKM[2]]
set_property DIFF_TERM false 		[get_ports m_AFE_DCLKP[2]]
set_property DIFF_TERM false 		[get_ports m_AFE_DCLKM[2]]
set_property DIFF_TERM false 		[get_ports m_AFE_FCLKP[3]]
set_property DIFF_TERM false 		[get_ports m_AFE_FCLKM[3]]
set_property DIFF_TERM false 		[get_ports m_AFE_DCLKP[3]]
set_property DIFF_TERM false 		[get_ports m_AFE_DCLKM[3]]

##-- AFE CONTROL --##
set_property PACKAGE_PIN AF24 		[get_ports m_AFE_SDIN[0]]
set_property PACKAGE_PIN V19 		[get_ports m_AFE_SDIN[1]]
set_property PACKAGE_PIN G25		[get_ports m_AFE_SDIN[2]]
set_property PACKAGE_PIN A17		[get_ports m_AFE_SDIN[3]]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_SDIN[0]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_SDIN[1]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_SDIN[2]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_SDIN[3]}]


####-- AFE LVDS --##
set_property PACKAGE_PIN AE23		[get_ports m_ADC_OUT_P_1[0 ]]
set_property PACKAGE_PIN AF23 		[get_ports m_ADC_OUT_N_1[0 ]]
set_property PACKAGE_PIN AE22 		[get_ports m_ADC_OUT_P_1[1 ]]
set_property PACKAGE_PIN AF22 		[get_ports m_ADC_OUT_N_1[1 ]]
set_property PACKAGE_PIN AC22 		[get_ports m_ADC_OUT_P_1[2 ]]
set_property PACKAGE_PIN AC23 		[get_ports m_ADC_OUT_N_1[2 ]]
set_property PACKAGE_PIN AD21 		[get_ports m_ADC_OUT_P_1[3 ]]
set_property PACKAGE_PIN AE21 		[get_ports m_ADC_OUT_N_1[3 ]]
set_property PACKAGE_PIN AD20 		[get_ports m_ADC_OUT_P_1[4 ]]
set_property PACKAGE_PIN AE20 		[get_ports m_ADC_OUT_N_1[4 ]]
set_property PACKAGE_PIN AE18 		[get_ports m_ADC_OUT_P_1[5 ]]
set_property PACKAGE_PIN AF18 		[get_ports m_ADC_OUT_N_1[5 ]]
set_property PACKAGE_PIN AF19 		[get_ports m_ADC_OUT_P_1[6 ]]
set_property PACKAGE_PIN AF20 		[get_ports m_ADC_OUT_N_1[6 ]]
set_property PACKAGE_PIN AE17 		[get_ports m_ADC_OUT_P_1[7 ]]
set_property PACKAGE_PIN AF17 		[get_ports m_ADC_OUT_N_1[7 ]]
set_property PACKAGE_PIN AC18 		[get_ports m_ADC_OUT_P_1[8 ]]
set_property PACKAGE_PIN AD18 		[get_ports m_ADC_OUT_N_1[8 ]]
set_property PACKAGE_PIN AC17		[get_ports m_ADC_OUT_P_1[9 ]]
set_property PACKAGE_PIN AD17 		[get_ports m_ADC_OUT_N_1[9 ]]
set_property PACKAGE_PIN Y18 		[get_ports m_ADC_OUT_P_1[10]]
set_property PACKAGE_PIN AA18 		[get_ports m_ADC_OUT_N_1[10]]
set_property PACKAGE_PIN AA17 		[get_ports m_ADC_OUT_P_1[11]]
set_property PACKAGE_PIN AB17 		[get_ports m_ADC_OUT_N_1[11]]
set_property PACKAGE_PIN AB16 		[get_ports m_ADC_OUT_P_1[12]]
set_property PACKAGE_PIN AC16 		[get_ports m_ADC_OUT_N_1[12]]
set_property PACKAGE_PIN Y16 		[get_ports m_ADC_OUT_P_1[13]]
set_property PACKAGE_PIN Y17 		[get_ports m_ADC_OUT_N_1[13]]
set_property PACKAGE_PIN Y15 		[get_ports m_ADC_OUT_P_1[14]]
set_property PACKAGE_PIN AA15 		[get_ports m_ADC_OUT_N_1[14]]
set_property PACKAGE_PIN W14 		[get_ports m_ADC_OUT_P_1[15]]
set_property PACKAGE_PIN W15 		[get_ports m_ADC_OUT_N_1[15]]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_1[0 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_1[0 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_1[1 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_1[1 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_1[2 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_1[2 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_1[3 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_1[3 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_1[4 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_1[4 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_1[5 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_1[5 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_1[6 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_1[6 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_1[7 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_1[7 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_1[8 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_1[8 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_1[9 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_1[9 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_1[10]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_1[10]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_1[11]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_1[11]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_1[12]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_1[12]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_1[13]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_1[13]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_1[14]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_1[14]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_1[15]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_1[15]}]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_1[0 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_1[0 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_1[1 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_1[1 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_1[2 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_1[2 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_1[3 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_1[3 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_1[4 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_1[4 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_1[5 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_1[5 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_1[6 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_1[6 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_1[7 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_1[7 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_1[8 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_1[8 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_1[9 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_1[9 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_1[10]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_1[10]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_1[11]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_1[11]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_1[12]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_1[12]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_1[13]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_1[13]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_1[14]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_1[14]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_1[15]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_1[15]]
	
set_property PACKAGE_PIN U25 		[get_ports m_ADC_OUT_P_2[0 ]]
set_property PACKAGE_PIN U26 		[get_ports m_ADC_OUT_N_2[0 ]]
set_property PACKAGE_PIN Y25		[get_ports m_ADC_OUT_P_2[1 ]]
set_property PACKAGE_PIN AA25 		[get_ports m_ADC_OUT_N_2[1 ]]
set_property PACKAGE_PIN AB24 		[get_ports m_ADC_OUT_P_2[2 ]]
set_property PACKAGE_PIN AC24 		[get_ports m_ADC_OUT_N_2[2 ]]
set_property PACKAGE_PIN AA24 		[get_ports m_ADC_OUT_P_2[3 ]]
set_property PACKAGE_PIN AB25 		[get_ports m_ADC_OUT_N_2[3 ]]
set_property PACKAGE_PIN V24 		[get_ports m_ADC_OUT_P_2[4 ]]
set_property PACKAGE_PIN W24 		[get_ports m_ADC_OUT_N_2[4 ]]
set_property PACKAGE_PIN V23 		[get_ports m_ADC_OUT_P_2[5 ]]
set_property PACKAGE_PIN W23 		[get_ports m_ADC_OUT_N_2[5 ]]
set_property PACKAGE_PIN AA22 		[get_ports m_ADC_OUT_P_2[6 ]]
set_property PACKAGE_PIN AA23 		[get_ports m_ADC_OUT_N_2[6 ]]
set_property PACKAGE_PIN W20 		[get_ports m_ADC_OUT_P_2[7 ]]
set_property PACKAGE_PIN Y20 		[get_ports m_ADC_OUT_N_2[7 ]]
set_property PACKAGE_PIN T20 		[get_ports m_ADC_OUT_P_2[8 ]]
set_property PACKAGE_PIN U20 		[get_ports m_ADC_OUT_N_2[8 ]]
set_property PACKAGE_PIN V18 		[get_ports m_ADC_OUT_P_2[9 ]]
set_property PACKAGE_PIN W18 		[get_ports m_ADC_OUT_N_2[9 ]]
set_property PACKAGE_PIN T19		[get_ports m_ADC_OUT_P_2[10]]
set_property PACKAGE_PIN U19 		[get_ports m_ADC_OUT_N_2[10]]
set_property PACKAGE_PIN T17		[get_ports m_ADC_OUT_P_2[11]]
set_property PACKAGE_PIN T18		[get_ports m_ADC_OUT_N_2[11]]
set_property PACKAGE_PIN V16		[get_ports m_ADC_OUT_P_2[12]]
set_property PACKAGE_PIN V17		[get_ports m_ADC_OUT_N_2[12]]
set_property PACKAGE_PIN U15 		[get_ports m_ADC_OUT_P_2[13]]
set_property PACKAGE_PIN U16 		[get_ports m_ADC_OUT_N_2[13]]
set_property PACKAGE_PIN T14		[get_ports m_ADC_OUT_P_2[14]]
set_property PACKAGE_PIN T15 		[get_ports m_ADC_OUT_N_2[14]]
set_property PACKAGE_PIN U14		[get_ports m_ADC_OUT_P_2[15]]
set_property PACKAGE_PIN V14 		[get_ports m_ADC_OUT_N_2[15]]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_2[0 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_2[0 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_2[1 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_2[1 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_2[2 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_2[2 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_2[3 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_2[3 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_2[4 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_2[4 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_2[5 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_2[5 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_2[6 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_2[6 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_2[7 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_2[7 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_2[8 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_2[8 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_2[9 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_2[9 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_2[10]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_2[10]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_2[11]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_2[11]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_2[12]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_2[12]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_2[13]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_2[13]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_2[14]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_2[14]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_2[15]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_2[15]}]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_2[0 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_2[0 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_2[1 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_2[1 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_2[2 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_2[2 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_2[3 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_2[3 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_2[4 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_2[4 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_2[5 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_2[5 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_2[6 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_2[6 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_2[7 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_2[7 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_2[8 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_2[8 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_2[9 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_2[9 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_2[10]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_2[10]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_2[11]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_2[11]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_2[12]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_2[12]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_2[13]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_2[13]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_2[14]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_2[14]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_2[15]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_2[15]]
	
set_property PACKAGE_PIN M14		[get_ports m_ADC_OUT_P_3[0 ]]
set_property PACKAGE_PIN L14		[get_ports m_ADC_OUT_N_3[0 ]]
set_property PACKAGE_PIN M15		[get_ports m_ADC_OUT_P_3[1 ]]
set_property PACKAGE_PIN L15		[get_ports m_ADC_OUT_N_3[1 ]]
set_property PACKAGE_PIN J14		[get_ports m_ADC_OUT_P_3[2 ]]
set_property PACKAGE_PIN J15		[get_ports m_ADC_OUT_N_3[2 ]]
set_property PACKAGE_PIN K15		[get_ports m_ADC_OUT_P_3[3 ]]
set_property PACKAGE_PIN J16		[get_ports m_ADC_OUT_N_3[3 ]]
set_property PACKAGE_PIN K16		[get_ports m_ADC_OUT_P_3[4 ]]
set_property PACKAGE_PIN K17		[get_ports m_ADC_OUT_N_3[4 ]]
set_property PACKAGE_PIN L17		[get_ports m_ADC_OUT_P_3[5 ]]
set_property PACKAGE_PIN L18		[get_ports m_ADC_OUT_N_3[5 ]]
set_property PACKAGE_PIN M16		[get_ports m_ADC_OUT_P_3[6 ]]
set_property PACKAGE_PIN M17		[get_ports m_ADC_OUT_N_3[6 ]]
set_property PACKAGE_PIN J18		[get_ports m_ADC_OUT_P_3[7 ]]
set_property PACKAGE_PIN H18		[get_ports m_ADC_OUT_N_3[7 ]]
set_property PACKAGE_PIN J19		[get_ports m_ADC_OUT_P_3[8 ]]
set_property PACKAGE_PIN H19		[get_ports m_ADC_OUT_N_3[8 ]]
set_property PACKAGE_PIN K20		[get_ports m_ADC_OUT_P_3[9 ]]
set_property PACKAGE_PIN J20		[get_ports m_ADC_OUT_N_3[9 ]]
set_property PACKAGE_PIN J24		[get_ports m_ADC_OUT_P_3[10]]
set_property PACKAGE_PIN H24		[get_ports m_ADC_OUT_N_3[10]]
set_property PACKAGE_PIN K22		[get_ports m_ADC_OUT_P_3[11]]
set_property PACKAGE_PIN K23		[get_ports m_ADC_OUT_N_3[11]]
set_property PACKAGE_PIN G22		[get_ports m_ADC_OUT_P_3[12]]
set_property PACKAGE_PIN F22		[get_ports m_ADC_OUT_N_3[12]]
set_property PACKAGE_PIN F23		[get_ports m_ADC_OUT_P_3[13]]
set_property PACKAGE_PIN E23		[get_ports m_ADC_OUT_N_3[13]]
set_property PACKAGE_PIN G24		[get_ports m_ADC_OUT_P_3[14]]
set_property PACKAGE_PIN F24		[get_ports m_ADC_OUT_N_3[14]]
set_property PACKAGE_PIN J25		[get_ports m_ADC_OUT_P_3[15]]
set_property PACKAGE_PIN J26		[get_ports m_ADC_OUT_N_3[15]]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_3[0 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_3[0 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_3[1 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_3[1 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_3[2 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_3[2 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_3[3 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_3[3 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_3[4 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_3[4 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_3[5 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_3[5 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_3[6 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_3[6 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_3[7 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_3[7 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_3[8 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_3[8 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_3[9 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_3[9 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_3[10]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_3[10]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_3[11]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_3[11]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_3[12]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_3[12]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_3[13]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_3[13]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_3[14]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_3[14]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_3[15]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_3[15]}]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_3[0 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_3[0 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_3[1 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_3[1 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_3[2 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_3[2 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_3[3 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_3[3 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_3[4 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_3[4 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_3[5 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_3[5 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_3[6 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_3[6 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_3[7 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_3[7 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_3[8 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_3[8 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_3[9 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_3[9 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_3[10]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_3[10]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_3[11]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_3[11]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_3[12]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_3[12]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_3[13]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_3[13]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_3[14]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_3[14]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_3[15]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_3[15]]
	
set_property PACKAGE_PIN H14		[get_ports m_ADC_OUT_P_4[0 ]]
set_property PACKAGE_PIN H15		[get_ports m_ADC_OUT_N_4[0 ]]
set_property PACKAGE_PIN G15		[get_ports m_ADC_OUT_P_4[1 ]]
set_property PACKAGE_PIN F15		[get_ports m_ADC_OUT_N_4[1 ]]
set_property PACKAGE_PIN H16		[get_ports m_ADC_OUT_P_4[2 ]]
set_property PACKAGE_PIN G16		[get_ports m_ADC_OUT_N_4[2 ]]
set_property PACKAGE_PIN G17		[get_ports m_ADC_OUT_P_4[3 ]]
set_property PACKAGE_PIN F17		[get_ports m_ADC_OUT_N_4[3 ]]
set_property PACKAGE_PIN F18		[get_ports m_ADC_OUT_P_4[4 ]]
set_property PACKAGE_PIN F19		[get_ports m_ADC_OUT_N_4[4 ]]
set_property PACKAGE_PIN G19		[get_ports m_ADC_OUT_P_4[5 ]]
set_property PACKAGE_PIN F20		[get_ports m_ADC_OUT_N_4[5 ]]
set_property PACKAGE_PIN E16		[get_ports m_ADC_OUT_P_4[6 ]]
set_property PACKAGE_PIN D16		[get_ports m_ADC_OUT_N_4[6 ]]
set_property PACKAGE_PIN E21		[get_ports m_ADC_OUT_P_4[7 ]]
set_property PACKAGE_PIN D21		[get_ports m_ADC_OUT_N_4[7 ]]
set_property PACKAGE_PIN D23		[get_ports m_ADC_OUT_P_4[8 ]]
set_property PACKAGE_PIN D24		[get_ports m_ADC_OUT_N_4[8 ]]
set_property PACKAGE_PIN C17		[get_ports m_ADC_OUT_P_4[9 ]]
set_property PACKAGE_PIN B17		[get_ports m_ADC_OUT_N_4[9 ]]
set_property PACKAGE_PIN C21		[get_ports m_ADC_OUT_P_4[10]]
set_property PACKAGE_PIN B21		[get_ports m_ADC_OUT_N_4[10]]
set_property PACKAGE_PIN C22		[get_ports m_ADC_OUT_P_4[11]]
set_property PACKAGE_PIN C23		[get_ports m_ADC_OUT_N_4[11]]
set_property PACKAGE_PIN C24		[get_ports m_ADC_OUT_P_4[12]]
set_property PACKAGE_PIN B24		[get_ports m_ADC_OUT_N_4[12]]
set_property PACKAGE_PIN C26		[get_ports m_ADC_OUT_P_4[13]]
set_property PACKAGE_PIN B26		[get_ports m_ADC_OUT_N_4[13]]
set_property PACKAGE_PIN B25		[get_ports m_ADC_OUT_P_4[14]]
set_property PACKAGE_PIN A25		[get_ports m_ADC_OUT_N_4[14]]
set_property PACKAGE_PIN A23		[get_ports m_ADC_OUT_P_4[15]]
set_property PACKAGE_PIN A24		[get_ports m_ADC_OUT_N_4[15]]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_4[0 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_4[0 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_4[1 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_4[1 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_4[2 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_4[2 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_4[3 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_4[3 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_4[4 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_4[4 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_4[5 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_4[5 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_4[6 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_4[6 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_4[7 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_4[7 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_4[8 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_4[8 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_4[9 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_4[9 ]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_4[10]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_4[10]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_4[11]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_4[11]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_4[12]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_4[12]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_4[13]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_4[13]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_4[14]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_4[14]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_P_4[15]}]
set_property IOSTANDARD LVDS_25 	[get_ports {m_ADC_OUT_N_4[15]}]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_4[0 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_4[0 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_4[1 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_4[1 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_4[2 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_4[2 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_4[3 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_4[3 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_4[4 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_4[4 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_4[5 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_4[5 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_4[6 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_4[6 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_4[7 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_4[7 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_4[8 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_4[8 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_4[9 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_4[9 ]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_4[10]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_4[10]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_4[11]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_4[11]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_4[12]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_4[12]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_4[13]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_4[13]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_4[14]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_4[14]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_P_4[15]]
set_property DIFF_TERM false 		[get_ports m_ADC_OUT_N_4[15]]

#### BATTERY ####
set_property PACKAGE_PIN N12 		[get_ports m_Battery_LEVEL]
set_property IOSTANDARD LVCMOS33  	[get_ports m_Battery_LEVEL]
set_property PACKAGE_PIN N18		[get_ports m_BATT_STAT1]
set_property IOSTANDARD LVCMOS33    [get_ports m_BATT_STAT1]

#### SWITCH ####
set_property PACKAGE_PIN W21 		[get_ports m_MODE_SWITCH]
set_property IOSTANDARD LVCMOS18    [get_ports m_MODE_SWITCH]
set_property PACKAGE_PIN Y21 		[get_ports m_SELECT_SWITCH]
set_property IOSTANDARD LVCMOS18    [get_ports m_SELECT_SWITCH]

#########################################################################################
#########################################################################################


#### CLOCK ####
##-- output --##
set_property PACKAGE_PIN P20		[get_ports m_FPGA_CLK_160M]
set_property IOSTANDARD LVCMOS33	[get_ports m_FPGA_CLK_160M]
set_property PACKAGE_PIN L22		[get_ports m_FPGA_CLK_40M_p]
set_property IOSTANDARD LVCMOS33	[get_ports m_FPGA_CLK_40M_p]
set_property DIFF_TERM false 		[get_ports m_FPGA_CLK_40M_p]
set_property PACKAGE_PIN L23		[get_ports m_FPGA_CLK_40M_n]
set_property IOSTANDARD LVCMOS33	[get_ports m_FPGA_CLK_40M_n]
set_property DIFF_TERM false 		[get_ports m_FPGA_CLK_40M_n]

#### POWER ####
set_property PACKAGE_PIN J8			[get_ports m_power_ON]
set_property IOSTANDARD LVCMOS33 	[get_ports {m_power_ON}]

## -- USB Control --##
set_property PACKAGE_PIN N3			[get_ports m_3014_VALID	]
set_property PACKAGE_PIN P6			[get_ports m_3014_POLLING_FLAG]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_VALID]
set_property IOSTANDARD LVCMOS33    [get_ports m_3014_POLLING_FLAG]

##-- AFE CONTROL --##
set_property PACKAGE_PIN AD23 		[get_ports m_AFE_SCLK_10M[0]]
set_property PACKAGE_PIN W25 		[get_ports m_AFE_SCLK_10M[1]]
set_property PACKAGE_PIN E25		[get_ports m_AFE_SCLK_10M[2]]
set_property PACKAGE_PIN B20		[get_ports m_AFE_SCLK_10M[3]]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_SCLK_10M[0]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_SCLK_10M[1]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_SCLK_10M[2]}]	
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_SCLK_10M[3]}]

set_property PACKAGE_PIN AE25 		[get_ports m_AFE_PDN_FAST[0]]
set_property PACKAGE_PIN V26 		[get_ports m_AFE_PDN_FAST[1]]
set_property PACKAGE_PIN E26		[get_ports m_AFE_PDN_FAST[2]]
set_property PACKAGE_PIN B22		[get_ports m_AFE_PDN_FAST[3]]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_PDN_FAST[0]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_PDN_FAST[1]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_PDN_FAST[2]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_PDN_FAST[3]}]

set_property PACKAGE_PIN AE26 		[get_ports m_AFE_PDN_GBL[0]]
set_property PACKAGE_PIN W26 		[get_ports m_AFE_PDN_GBL[1]]
set_property PACKAGE_PIN D26		[get_ports m_AFE_PDN_GBL[2]]
set_property PACKAGE_PIN A22		[get_ports m_AFE_PDN_GBL[3]]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_PDN_GBL[0]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_PDN_GBL[1]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_PDN_GBL[2]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_PDN_GBL[3]}]

set_property PACKAGE_PIN AF25 		[get_ports m_AFE_SDOUT[0]]
set_property PACKAGE_PIN W19 		[get_ports m_AFE_SDOUT[1]]
set_property PACKAGE_PIN F25		[get_ports m_AFE_SDOUT[2]]
set_property PACKAGE_PIN A18		[get_ports m_AFE_SDOUT[3]]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_SDOUT[0]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_SDOUT[1]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_SDOUT[2]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_SDOUT[3]}]

set_property PACKAGE_PIN AD25 		[get_ports m_AFE_SEN[0]]
set_property PACKAGE_PIN AB26 		[get_ports m_AFE_SEN[1]]
set_property PACKAGE_PIN H26		[get_ports m_AFE_SEN[2]]
set_property PACKAGE_PIN B19		[get_ports m_AFE_SEN[3]]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_SEN[0]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_SEN[1]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_SEN[2]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_SEN[3]}]

set_property PACKAGE_PIN AD26 		[get_ports m_AFE_RESET[0]]
set_property PACKAGE_PIN AC26 		[get_ports m_AFE_RESET[1]]
set_property PACKAGE_PIN G26		[get_ports m_AFE_RESET[2]]
set_property PACKAGE_PIN A19		[get_ports m_AFE_RESET[3]]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_RESET[0]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_RESET[1]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_RESET[2]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_RESET[3]}]

set_property PACKAGE_PIN AD24 		[get_ports m_AFE_TX_TRIG[0]]
set_property PACKAGE_PIN Y26 		[get_ports m_AFE_TX_TRIG[1]]
set_property PACKAGE_PIN D25		[get_ports m_AFE_TX_TRIG[2]]
set_property PACKAGE_PIN A20		[get_ports m_AFE_TX_TRIG[3]]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_TX_TRIG[0]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_TX_TRIG[1]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_TX_TRIG[2]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_AFE_TX_TRIG[3]}]

### HV CONTROL ####
set_property PACKAGE_PIN P21		[get_ports m_3V3ND_Ctrl]
set_property IOSTANDARD LVCMOS33	[get_ports {m_3V3ND_Ctrl}]
set_property PACKAGE_PIN E22		[get_ports m_Pulser_3V3_Ctrl]
set_property IOSTANDARD LVCMOS18	[get_ports {m_Pulser_3V3_Ctrl}]
set_property PACKAGE_PIN AB22 		[get_ports m_HV_40VP_EN]
set_property IOSTANDARD LVCMOS18 	[get_ports {m_HV_40VP_EN}]
set_property PACKAGE_PIN W16 		[get_ports m_HV_80VP_EN]
set_property IOSTANDARD LVCMOS18	[get_ports {m_HV_80VP_EN}]
set_property PACKAGE_PIN U24 		[get_ports m_HV_40VN_EN]
set_property IOSTANDARD LVCMOS18    [get_ports {m_HV_40VN_EN}]
set_property PACKAGE_PIN U17		[get_ports m_HV_80VN_EN]
set_property IOSTANDARD LVCMOS18    [get_ports {m_HV_80VN_EN}]
set_property PACKAGE_PIN P4			[get_ports m_HV_80_VIN_CTRL]
set_property IOSTANDARD LVCMOS33    [get_ports {m_HV_80_VIN_CTRL}]
set_property PACKAGE_PIN P16		[get_ports m_HV_DROP_pos]
set_property IOSTANDARD LVCMOS33    [get_ports {m_HV_DROP_pos}]
set_property PACKAGE_PIN P15		[get_ports m_HV_DROP_neg]
set_property IOSTANDARD LVCMOS33    [get_ports {m_HV_DROP_neg}]

#### DEBUG ####
set_property PACKAGE_PIN N4			[get_ports m_DEBUG_LED]
set_property IOSTANDARD LVCMOS33 	[get_ports {m_DEBUG_LED}]
set_property PACKAGE_PIN V4			[get_ports m_DEBUG_3V3_1]
set_property IOSTANDARD LVCMOS33 	[get_ports {m_DEBUG_3V3_1}]
set_property PACKAGE_PIN V9			[get_ports m_DEBUG_3V3_2]
set_property IOSTANDARD LVCMOS33	[get_ports {m_DEBUG_3V3_2}]
set_property PACKAGE_PIN R3			[get_ports m_DEBUG_3V3_3]
set_property IOSTANDARD LVCMOS33	[get_ports {m_DEBUG_3V3_3}]
set_property PACKAGE_PIN AC19 		[get_ports m_DEBUG_1V8_1]
set_property IOSTANDARD LVCMOS18	[get_ports {m_DEBUG_1V8_1}]
set_property PACKAGE_PIN AD19 		[get_ports m_DEBUG_1V8_2]
set_property IOSTANDARD LVCMOS18	[get_ports {m_DEBUG_1V8_2}]
set_property PACKAGE_PIN J23		[get_ports m_DEBUG_1V8_3]
set_property IOSTANDARD LVCMOS18	[get_ports {m_DEBUG_1V8_3}]

#### Pulser CONTROL ####
##-- Control --##
set_property PACKAGE_PIN R18		[get_ports m_CW]
set_property PACKAGE_PIN M19		[get_ports m_THSD]
set_property IOSTANDARD LVCMOS33	[get_ports {m_CW}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_THSD}]
##-- CH1 --##
set_property PACKAGE_PIN W3			[get_ports m_IN1_P[0]]
set_property PACKAGE_PIN Y3			[get_ports m_IN1_N[0]]
set_property PACKAGE_PIN W5			[get_ports m_IN1_P[1]]
set_property PACKAGE_PIN W4			[get_ports m_IN1_N[1]]
set_property PACKAGE_PIN V1			[get_ports m_IN1_P[2]]
set_property PACKAGE_PIN W1			[get_ports m_IN1_N[2]]
set_property PACKAGE_PIN V3			[get_ports m_IN1_P[3]]
set_property PACKAGE_PIN V2			[get_ports m_IN1_N[3]]
set_property PACKAGE_PIN AB1		[get_ports m_IN1_P[4]]
set_property PACKAGE_PIN AC1		[get_ports m_IN1_N[4]]
set_property PACKAGE_PIN AA3		[get_ports m_IN1_P[5]]
set_property PACKAGE_PIN AA2		[get_ports m_IN1_N[5]]
set_property PACKAGE_PIN AA4		[get_ports m_IN1_P[6]]
set_property PACKAGE_PIN AB4		[get_ports m_IN1_N[6]]
set_property PACKAGE_PIN Y2			[get_ports m_IN1_P[7]]
set_property PACKAGE_PIN Y1			[get_ports m_IN1_N[7]]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN1_P[0]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN1_N[0]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN1_P[1]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN1_N[1]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN1_P[2]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN1_N[2]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN1_P[3]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN1_N[3]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN1_P[4]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN1_N[4]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN1_P[5]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN1_N[5]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN1_P[6]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN1_N[6]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN1_P[7]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN1_N[7]}]
##-- CH2 --##
set_property PACKAGE_PIN AC3		[get_ports m_IN2_P[0]]
set_property PACKAGE_PIN AD3		[get_ports m_IN2_N[0]]
set_property PACKAGE_PIN AE2		[get_ports m_IN2_P[1]]
set_property PACKAGE_PIN AF2		[get_ports m_IN2_N[1]]
set_property PACKAGE_PIN AB2		[get_ports m_IN2_P[2]]
set_property PACKAGE_PIN AC2		[get_ports m_IN2_N[2]]
set_property PACKAGE_PIN AD1		[get_ports m_IN2_P[3]]
set_property PACKAGE_PIN AE1		[get_ports m_IN2_N[3]]
set_property PACKAGE_PIN AD5		[get_ports m_IN2_P[4]]
set_property PACKAGE_PIN AE5		[get_ports m_IN2_N[4]]
set_property PACKAGE_PIN AF5		[get_ports m_IN2_P[5]]
set_property PACKAGE_PIN AF4		[get_ports m_IN2_N[5]]
set_property PACKAGE_PIN AC4		[get_ports m_IN2_P[6]]
set_property PACKAGE_PIN AD4		[get_ports m_IN2_N[6]]
set_property PACKAGE_PIN AE3		[get_ports m_IN2_P[7]]
set_property PACKAGE_PIN AF3		[get_ports m_IN2_N[7]]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN2_P[0]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN2_N[0]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN2_P[1]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN2_N[1]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN2_P[2]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN2_N[2]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN2_P[3]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN2_N[3]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN2_P[4]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN2_N[4]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN2_P[5]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN2_N[5]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN2_P[6]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN2_N[6]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN2_P[7]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN2_N[7]}]
####-- CH3 --##
set_property PACKAGE_PIN AB6		[get_ports m_IN3_P[0]]
set_property PACKAGE_PIN AC6		[get_ports m_IN3_N[0]]
set_property PACKAGE_PIN V6			[get_ports m_IN3_P[1]]
set_property PACKAGE_PIN W6			[get_ports m_IN3_N[1]]
set_property PACKAGE_PIN Y6			[get_ports m_IN3_P[2]]
set_property PACKAGE_PIN Y5			[get_ports m_IN3_N[2]]
set_property PACKAGE_PIN AA5		[get_ports m_IN3_P[3]]
set_property PACKAGE_PIN AB5		[get_ports m_IN3_N[3]]
set_property PACKAGE_PIN Y8			[get_ports m_IN3_P[4]]
set_property PACKAGE_PIN AA8		[get_ports m_IN3_N[4]]
set_property PACKAGE_PIN V8			[get_ports m_IN3_P[5]]
set_property PACKAGE_PIN W8			[get_ports m_IN3_N[5]]
set_property PACKAGE_PIN Y7			[get_ports m_IN3_P[6]]
set_property PACKAGE_PIN AA7		[get_ports m_IN3_N[6]]
set_property PACKAGE_PIN U7			[get_ports m_IN3_P[7]]
set_property PACKAGE_PIN V7			[get_ports m_IN3_N[7]]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN3_P[0]}]
set_property IOSTANDARD LVCMOS33    [get_ports {m_IN3_N[0]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN3_P[1]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN3_N[1]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN3_P[2]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN3_N[2]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN3_P[3]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN3_N[3]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN3_P[4]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN3_N[4]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN3_P[5]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN3_N[5]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN3_P[6]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN3_N[6]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN3_P[7]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN3_N[7]}]
##-- CH4 --##
set_property PACKAGE_PIN T23		[get_ports m_IN4_P[0]]
set_property PACKAGE_PIN R23		[get_ports m_IN4_N[0]]
set_property PACKAGE_PIN T22		[get_ports m_IN4_P[1]]
set_property PACKAGE_PIN R22		[get_ports m_IN4_N[1]]
set_property PACKAGE_PIN R20		[get_ports m_IN4_P[2]]
set_property PACKAGE_PIN R21		[get_ports m_IN4_N[2]]
set_property PACKAGE_PIN P19		[get_ports m_IN4_P[3]]
set_property PACKAGE_PIN N19		[get_ports m_IN4_N[3]]
set_property PACKAGE_PIN R26		[get_ports m_IN4_P[4]]
set_property PACKAGE_PIN P26		[get_ports m_IN4_N[4]]
set_property PACKAGE_PIN R25		[get_ports m_IN4_P[5]]
set_property PACKAGE_PIN P25		[get_ports m_IN4_N[5]]
set_property PACKAGE_PIN T24		[get_ports m_IN4_P[6]]
set_property PACKAGE_PIN T25		[get_ports m_IN4_N[6]]
set_property PACKAGE_PIN P23		[get_ports m_IN4_P[7]]
set_property PACKAGE_PIN P24		[get_ports m_IN4_N[7]]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN4_P[0]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN4_N[0]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN4_P[1]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN4_N[1]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN4_P[2]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN4_N[2]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN4_P[3]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN4_N[3]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN4_P[4]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN4_N[4]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN4_P[5]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN4_N[5]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN4_P[6]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN4_N[6]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN4_P[7]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN4_N[7]}]
##-- CH5 --##
set_property PACKAGE_PIN L24		[get_ports m_IN5_P[0]]
set_property PACKAGE_PIN L25		[get_ports m_IN5_N[0]]
set_property PACKAGE_PIN M24		[get_ports m_IN5_P[1]]
set_property PACKAGE_PIN M25		[get_ports m_IN5_N[1]]
set_property PACKAGE_PIN N23		[get_ports m_IN5_P[2]]
set_property PACKAGE_PIN N24		[get_ports m_IN5_N[2]]
set_property PACKAGE_PIN N26		[get_ports m_IN5_P[3]]
set_property PACKAGE_PIN M26		[get_ports m_IN5_N[3]]
set_property PACKAGE_PIN R16		[get_ports m_IN5_P[4]]
set_property PACKAGE_PIN R17		[get_ports m_IN5_N[4]]
set_property PACKAGE_PIN N16		[get_ports m_IN5_P[5]]
set_property PACKAGE_PIN N17		[get_ports m_IN5_N[5]]
set_property PACKAGE_PIN M20		[get_ports m_IN5_P[6]]
set_property PACKAGE_PIN L20		[get_ports m_IN5_N[6]]
set_property PACKAGE_PIN K25		[get_ports m_IN5_P[7]]
set_property PACKAGE_PIN K26		[get_ports m_IN5_N[7]]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN5_P[0]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN5_N[0]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN5_P[1]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN5_N[1]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN5_P[2]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN5_N[2]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN5_P[3]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN5_N[3]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN5_P[4]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN5_N[4]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN5_P[5]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN5_N[5]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN5_P[6]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN5_N[6]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN5_P[7]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN5_N[7]}]
##-- CH6 --##
set_property PACKAGE_PIN H7			[get_ports m_IN6_P[0]]
set_property PACKAGE_PIN G7			[get_ports m_IN6_N[0]]
set_property PACKAGE_PIN L8			[get_ports m_IN6_P[1]]
set_property PACKAGE_PIN K8			[get_ports m_IN6_N[1]]
set_property PACKAGE_PIN H8			[get_ports m_IN6_P[2]]
set_property PACKAGE_PIN G8			[get_ports m_IN6_N[2]]
set_property PACKAGE_PIN H9			[get_ports m_IN6_P[3]]
set_property PACKAGE_PIN G9			[get_ports m_IN6_N[3]]
set_property PACKAGE_PIN J4			[get_ports m_IN6_P[4]]
set_property PACKAGE_PIN H4			[get_ports m_IN6_N[4]]
set_property PACKAGE_PIN J6			[get_ports m_IN6_P[5]]
set_property PACKAGE_PIN J5			[get_ports m_IN6_N[5]]
set_property PACKAGE_PIN H6			[get_ports m_IN6_P[6]]
set_property PACKAGE_PIN G6			[get_ports m_IN6_N[6]]
set_property PACKAGE_PIN K7			[get_ports m_IN6_P[7]]
set_property PACKAGE_PIN K6			[get_ports m_IN6_N[7]]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN6_P[0]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN6_N[0]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN6_P[1]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN6_N[1]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN6_P[2]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN6_N[2]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN6_P[3]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN6_N[3]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN6_P[4]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN6_N[4]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN6_P[5]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN6_N[5]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN6_P[6]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN6_N[6]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN6_P[7]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN6_N[7]}]
##-- CH7 --##
set_property PACKAGE_PIN F3			[get_ports m_IN7_P[0]]
set_property PACKAGE_PIN E3			[get_ports m_IN7_N[0]]
set_property PACKAGE_PIN G4			[get_ports m_IN7_P[1]]
set_property PACKAGE_PIN F4			[get_ports m_IN7_N[1]]
set_property PACKAGE_PIN G5			[get_ports m_IN7_P[2]]
set_property PACKAGE_PIN F5			[get_ports m_IN7_N[2]]
set_property PACKAGE_PIN F8			[get_ports m_IN7_P[3]]
set_property PACKAGE_PIN F7			[get_ports m_IN7_N[3]]
set_property PACKAGE_PIN E1			[get_ports m_IN7_P[4]]
set_property PACKAGE_PIN D1			[get_ports m_IN7_N[4]]
set_property PACKAGE_PIN G2			[get_ports m_IN7_P[5]]
set_property PACKAGE_PIN G1			[get_ports m_IN7_N[5]]
set_property PACKAGE_PIN F2			[get_ports m_IN7_P[6]]
set_property PACKAGE_PIN E2			[get_ports m_IN7_N[6]]
set_property PACKAGE_PIN C2			[get_ports m_IN7_P[7]]
set_property PACKAGE_PIN B2			[get_ports m_IN7_N[7]]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN7_P[0]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN7_N[0]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN7_P[1]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN7_N[1]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN7_P[2]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN7_N[2]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN7_P[3]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN7_N[3]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN7_P[4]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN7_N[4]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN7_P[5]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN7_N[5]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN7_P[6]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN7_N[6]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN7_P[7]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN7_N[7]}]
##-- CH8 --##
set_property PACKAGE_PIN B4			[get_ports m_IN8_P[0]]
set_property PACKAGE_PIN A4			[get_ports m_IN8_N[0]]
set_property PACKAGE_PIN E5			[get_ports m_IN8_P[1]]
set_property PACKAGE_PIN D5			[get_ports m_IN8_N[1]]
set_property PACKAGE_PIN B5			[get_ports m_IN8_P[2]]
set_property PACKAGE_PIN A5			[get_ports m_IN8_N[2]]
set_property PACKAGE_PIN E6			[get_ports m_IN8_P[3]]
set_property PACKAGE_PIN D6			[get_ports m_IN8_N[3]]
set_property PACKAGE_PIN C1			[get_ports m_IN8_P[4]]
set_property PACKAGE_PIN B1			[get_ports m_IN8_N[4]]
set_property PACKAGE_PIN A3			[get_ports m_IN8_P[5]]
set_property PACKAGE_PIN A2			[get_ports m_IN8_N[5]]
set_property PACKAGE_PIN D3			[get_ports m_IN8_P[6]]
set_property PACKAGE_PIN C3			[get_ports m_IN8_N[6]]
set_property PACKAGE_PIN D4			[get_ports m_IN8_P[7]]
set_property PACKAGE_PIN C4			[get_ports m_IN8_N[7]]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN8_P[0]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN8_N[0]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN8_P[1]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN8_N[1]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN8_P[2]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN8_N[2]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN8_P[3]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN8_N[3]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN8_P[4]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN8_N[4]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN8_P[5]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN8_N[5]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN8_P[6]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN8_N[6]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN8_P[7]}]
set_property IOSTANDARD LVCMOS33	[get_ports {m_IN8_N[7]}]


#### Digital Potentiometer CONTROL ####
set_property PACKAGE_PIN M4			[get_ports m_I2C_SCL[0]]
set_property PACKAGE_PIN L4			[get_ports m_I2C_SDA[0]]
set_property PACKAGE_PIN N1			[get_ports m_I2C_SCL[1]]
set_property PACKAGE_PIN M1			[get_ports m_I2C_SDA[1]]
set_property IOSTANDARD LVCMOS33    [get_ports m_I2C_SCL[0]]
set_property IOSTANDARD LVCMOS33    [get_ports m_I2C_SDA[0]]
set_property IOSTANDARD LVCMOS33    [get_ports m_I2C_SCL[1]]
set_property IOSTANDARD LVCMOS33    [get_ports m_I2C_SDA[1]]

###### LCD CONTROL ####--수정중
##set_property PACKAGE_PIN T2			[get_ports m_DSI_SCL0]
##set_property PACKAGE_PIN R2			[get_ports m_DSI_SDA0]
##set_property IOSTANDARD LVCMOS33    [get_ports m_DSI_SCL0]
##set_property IOSTANDARD LVCMOS33    [get_ports m_DSI_SDA0]
